version: '3.8'

services:
  frontend:
    container_name: bakery_system_frontend
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./nodemon.json:/usr/src/app/nodemon.json
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: npm run start
